version: 0.1.0.{build}

image: Visual Studio 2015

configuration: Release
platform: Any CPU

build:
  project: Jam.NET.sln

before_build:
 - nuget restore

after_build:
 - >
   7z a Jam.NET-%APPVEYOR_BUILD_VERSION%.zip 
   %APPVEYOR_BUILD_FOLDER%\bin\Release\Jam.NET.exe 
   %APPVEYOR_BUILD_FOLDER%\bin\Release\Jam.NET.exe.config
   %APPVEYOR_BUILD_FOLDER%\bin\Release\NAudio.dll
   %APPVEYOR_BUILD_FOLDER%\bin\Release\plist-cil.dll
   %APPVEYOR_BUILD_FOLDER%\README.md
   %APPVEYOR_BUILD_FOLDER%\COPYING



artifacts:
 - path: Jam.NET-%APPVEYOR_BUILD_VERSION%.zip
